[workspace]
members = [
    "examples/*",
    "yarte",
    "yarte_codegen",
    "yarte_derive",
    "yarte_helpers",
    "yarte_hir",
    "yarte_html",
    "yarte_lexer",
    "yarte_parser",
    "yarte_rust",
    "yarte_strnom",
]
